environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

init:
    - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
    - "%PYTHON%\\python -m pip install --upgrade pip"
    - "%PYTHON%\\Scripts\\pip install -r requirements.txt"
    - "%PYTHON%\\Scripts\\pip install git+https://github.com/apple/coremltools"
    - if %%PYTHON%==C:\\Python36-x64 "%PYTHON%\\Scripts\\pip install https://github.com/xadupre/xgboost/releases/download/0.7/xgboost-0.7-cp36-cp36m-win_amd64.whl"
    - "%PYTHON%\\Scripts\\pip install -r requirements-dev.txt"
    - set PYTHONPATH=%~dp0

build: off

test_script:
    - "%PYTHON%\\python -m pytest --cov=onnxmltools --cov-report=term --cov-report=html --cov-report=xml tests"

after_test:
    - "%PYTHON%\\python -u setup.py bdist_wheel"
    - if not exist dist mkdir dist
    - if not exist dist\htmlcov mkdir dist\htmlcov
    - xcopy htmlcov dist\htmlcov
    - copy *.xml dist\htmlcov

artifacts:
    - path: dist
      name: onnxmltools
    